spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/forumspace
        username:
        password:
    jpa:
        hibernate:
            # dialect: org.hibernate.dialect.PostgreSQLDialect
            # format_sql: true
            ddl-auto: create-drop
        show-sql: true

server.error.include-message: always
